name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

  show-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Read project version
        id: read-version
        run: |
          echo "::set-output name=project-version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      - name: Write project version
        run: |
          echo "variables read:"
          echo "${{join(steps.read-version.outputs.*, '\n')}}"
          echo "project version:"
          echo "${{steps.read-version.outputs.project-version}}"
