name: Prepare release

on:
  push:
    branches:
      - test

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
              mvn clean install
              mvn validate -DbumpMinor
              mvn versions:commit
      - name: Create release branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create release branch
          branch: release
          create_branch: true
          file_pattern: pom.xml
