name: Prepare release

on:
  push:
    branches:
      - test

jobs:
  show-refs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to production server on branch $GITHUB_REF"
          echo "head_ref: $GITHUB_HEAD_REF"
          echo "event name: $GITHUB_EVENT_NAME"
          echo "ref name: $GITHUB_REF_NAME"
