name: Prepare release

on:
  push:
    branches:
      - test

jobs:
  show-refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repository

      - name: get reference
        run: |
          PARENT_BRANCH=git show-branch -a \
          | grep '\*' \
          | grep -v `git rev-parse --abbrev-ref HEAD` \
          | head -n1 \
          | sed 's/.*\[\(.*\)\].*/\1/' \
          | sed 's/[\^~].*//'
          echo "parent branch: $PARENT_BRANCH"
