name: Prepare release

on:
  workflow_dispatch:
    inputs:
      increase-version:
        description: 'Release level'
        required: true
        default: 'Minor'
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repository

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set new version
        run: mvn validate -Dbump${{ github.event.inputs.increase-version }}

      - name: Read new project version
        id: read-version
        run: echo "::set-output name=project-version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
  
      - name: Create branch release/v${{ github.event.inputs.increase-version }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create release branch
          branch: release/v${{steps.read-version.outputs.project-version}}
          create_branch: true
          file_pattern: pom.xml
  sync-main-branch:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Merge release/v${{steps.read-version.outputs.project-version}} -> main
        run: echo "merge release/v${{steps.read-version.outputs.project-version}} -> main"

  sync-develop-branch:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Merge release/v${{steps.read-version.outputs.project-version}} -> develop
        run: echo "merge release/v${{steps.read-version.outputs.project-version}} -> develop"
  
  delete-release-branch:
    needs: [sync-main-branch, sync-develop-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch release/v${{steps.read-version.outputs.project-version}}
        uses: dawidd6/action-delete-branch@v3.1.0
        with:
          branches: release/v${{steps.read-version.outputs.project-version}}



