name: Prepare release

on:
  workflow_dispatch:
    inputs:
      increase-version:
        description: 'Release level'
        required: true
        default: 'Minor'
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repository

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set new version
        run: mvn validate -Dbump${{ github.event.inputs.increase-version }}

      - name: Read new project version
        id: read-version
        run: echo "::set-output name=project-version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          
      - name: Create release branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create release branch
          branch: release/${{steps.read-version.outputs.project-version}}
          create_branch: true
          file_pattern: pom.xml
